# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: gitlab.er.kcl.ac.uk:4567/infra/py-webfarmd

stages:
  - lint
  - tests
  - build

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - poetry config virtualenvs.create false
  - poetry config http-basic.py-sci-common gitlab-ci-token ${CI_JOB_TOKEN}
  - poetry install

Python Code Lint:
  stage: lint
  script:
    - poetry run black ./webfarmd

Unit Tests:
  stage: tests
  script:
    - poetry run pytest --cov=webfarmd  --junitxml=report.xml tests/
  artifacts:
    when: always
    reports:
      junit: report.xml

Deploy:
  stage: build
  script:
    - poetry config repositories.ergitlab ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi
    - poetry publish --build -r ergitlab --username gitlab-ci-token --password ${CI_JOB_TOKEN}
  only:
    - tags
